OPENAI_API_KEY = "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"


google_api_key = "AIzaSyCNStESbhb-fehM09H2XW3Uno1FhMASvcQ"